### ISSUE TITLE
Does it work with hosted agent of Visual studio 2015?

### ISSUE THREAD

**Issue by ashish1137** [Rogeriohsjr/CoverageConverter#1]
Hi There,

This is an awesome extension. I can use it as yaml. How can I use it as a step in azure pipeline. My hosted agent has Visual Studio 2015

Thanks
Ashish

**Comment by Rogeriohsjr** [comment]
Hey There,

Thank you for the comment. I believe it does, did you try to chance the path to 2015 when you add the Task into your pipeline?

The Coverage.exe file is available only for Visual Studio Enterprise or Professional. If you are using the Azure Hosted Agent, you should be good.

Here is one example how the pipeline looks like:
https://github.com/Rogeriohsjr/AzureDevOpsTask/blob/master/buildAndReleaseTask/index.ts

Let me know if that works for you,

**Comment by ashish1137** [comment]
Hi Rogeriohsjr,

I have managed to build the solution in 2015.
[azure-pipeline.txt](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/3915493/azure-pipeline.txt)
I attached the pipeline. It matches mostly with what you have suggested.
[Code Coverage Report_285.zip](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/3915501/Code.Coverage.Report_285.zip)

But the report generated is not my test result. There were over 2000 tests but none of them are in the report. Please guide.

Thanks
Ashish

**Comment by ashish1137** [comment]
Hi Rogeriohsjr,

We are using NUnit test. If you see my pipeline which I had attached earlier, I am running NUnit tests. Does your tool support NUnit? If yes, how do I use that?

Thanks in advance.
Ashish

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 , 

Another thing you can try is to get the XML that the vsTest executed, and check what is inside, if your test is there, you should also see that the vsTest had run all your tests, if you don't see that in the log, it means that vsTest needs more configuration.

Could you post the Log from CoverageConverter@0 and VSTest@2 that you have? Also, can you set the Debug=true variable and Diagnostic=on as well?

Just a heads up that this extension only executes the vsTest to get the code coverage and execute the CodeCoverage.exe to convert the files. I don't generate any code coverage or I don't covert anything, it is all Microsoft, by the report that you sent, it seems that the convertion is working.

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 , try to get the latest version 0.1.21, there was a bug that the extension was not converting if we had two projects.

**Comment by ashish1137** [comment]
Hi Rogeriohsr,

When I try to reinstall from marketplace I get error "This extension is already installed on this organization"
I think I have found the issue. My tests are NUnit test not VSTest. Hence "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" needs adapter. While running the unit test I had provided that as "pathtoCustomTestAdapters". Is there a similar thing in "- task: CoverageConverter@0"?
[Tests log.zip](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/3920407/Tests.log.zip)
[coverageconverter log.zip](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/3920408/coverageconverter.log.zip)
This shows that 2107 tests passed. If I get this working it will be really a  great help.


Thanks
Ashish

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 , uninstall and install again, you don't need to remove from your pipeline, sometimes for the update you don't need to uninstall, but by the log you sent me it seems that you are using an old version, and yes, you have many projects, I wasn't supporting this scenario, now I am, the new version should fix.

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 , did you have a chance to test it?

**Comment by ashish1137** [comment]
Hi Rogeriosjr,

Unfortunately it didn’t work for me. But thanks anyway.

Thanks
Ashish

**Comment by ashish1137** [comment]
Hi Rgeriohsjr,

Hope you are doing well.
Do you have any more suggestions? Does it support NUnit tests?

Thanks
Ashish

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 , can you add the log again with the new version?

Make sure you are using the new version, it should be version:  0.1.21

**Comment by ashish1137** [comment]
[pipeline.txt](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/3964754/pipeline.txt)
[Coverageconverter.zip](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/3964750/Coverageconverter.zip)
[vstest2.zip](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/3964751/vstest2.zip)


Hi Rogeriohsjr,

My name is Ashish :)

There are few things to notice.


   1. VSTest2 : Search folder is '$(build.artifactStagingDirectory)' not
   $(System.DefaultWorkingDirectory). 44 tests passed.(I removed rest of the
   tests to keep it simple)
   2. CoverageConverter@0 : There is nothing that matched
listTestFiles: '**\bin\**\*.Test*.dll'.
    If I change to -  listTestFiles: '**\*.Test*.dll'  then I get something
   that matches but covered lines are 0.

I have attached all the files. If required, can we do a screenshare session
where I can share my laptop's screen with you.

Many Thanks
Ashish

**Comment by ashish1137** [comment]
Hi Rogeriohsjr,

Did you get a chance to look into the logs?

Thanks 
Ashish

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 , thank you for sharing the log, yes, I took in the log and CoverageConverter doesn't support this scenario.

If you look at your VSTest log that you shared, you will see that Azure DevOps Pipeline for the VSTest Task executes the vstest.exe using a temporary file instead of a dll.

Here is the log from your VSTest log:
2019-12-15T08:57:48.0460154Z [command]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@d:\a\_temp\5yl425k2vnw.tmp"

The CoverageConverter execute only the dll, we search for the Test.dll in the project, then we execute like this:
2019-12-15T08:57:48.0460154Z [command]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe /EnableCodeCoverage "@d:\a\1\a\Landata.Server.App.UnitTest.dll"

This command will generate the coverage.xml file which after we will get this file and convert into a xml for the Report to read this file.

It seems that we don't support NUnit, I can try to create a project and see how it goes and if there is a workaround, but that won't be this year or January because I am pretty busy on these dates. Feel free to analyze the extension and change as your need.

If I change that, I will let you know. Thank you for trying to use the extension.

**Comment by ashish1137** [comment]
Thanks, Rogerio! for the update. Happy new year in advance :)

**Comment by ashish1137** [comment]
Hi Rogeriohsjr,

Happy New Year!

I was wondering if there’s a way to read .coverage file generated by Azure
DevOps in Code coverage tab. The .coverage file generated by the build
pipeline gives accurate result when I view in Visual Studio. All I want is
a way to view that in code coverage tab instead of downloading and opening
in visual studio.

Thanks
Ashish

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 ,
Happy new year! 

Yes, I understand you, I wanted the same thing, and I end up building this because AzureDevOps doesn't support that out of the box.

Which stack are you using? NUnit + .Net Core Web API ?

Could you share a log from CoverageConverter again but with debug on, last time you shared the CoverageConverter with no debug, so I don't know why we didn't find the file.

**Comment by ashish1137** [comment]
Hi Rogeriohsjr,

I added following lines to CodeConverter

    debug: true
    diagnosticsEnabled: True

I have attached the log 
[log_12_413.zip](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/4080069/log_12_413.zip)

The 'Code Coverage' tab says 'No code coverage data available.'.
I am using Asp.Net 4.6 and NUnit.

Thanks
Ashish

**Comment by Rogeriohsjr** [comment]
The log that you shared, shows that we processed 5 projects(dlls) and was converted all the 5 .coverage to xml.
Did you add the reportgenerator@4 and PublishCodeCoverageResults@1 in your pipeline after the CoverageConverter@0?

You should add these after CoverageConverter@0.
`
- task: reportgenerator@4
  displayName: 'Generate Coverage Report'
  inputs:
    reports: '$(Agent.TempDirectory)\TestResults\DynamicCodeCoverage.coveragexml'
    targetdir: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports'
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Coverage Report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports\Cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports'
`

**Comment by ashish1137** [comment]
Hi Rogeriohsjr,

I had added those steps. The entire pipeline is 
[pipeline.txt](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/4082396/pipeline.txt)

One thing that I noticed is 

CoverageConverter@0 : There is nothing that matched
listTestFiles: '**\bin\**\*.Test*.dll'.
    If I change to -  listTestFiles: '**\*.Test*.dll'  then I get something
   that matches but covered lines are 0.

Thanks
Ashish

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 , try to change the listTestFiles to be "**\*Test*.dll" like your NUnitMatchPattern variable.

I will create a project with Asp.Net and NUnit to see if that works. I will put here the results.

**Comment by Rogeriohsjr** [comment]
Hey @ashish1137 , I have created a project using Asp.Net Framework 4.6 with NUnit, and I didn't have any problem, I could see all the Unit Test.

Here is the pipeline file:
https://github.com/Rogeriohsjr/AspNetProjectWithNUnit/blob/master/azure-pipelines.yml

I would say check the name of the Test Project that you create, as I said in my last comment.

If that still not working, if you can duplicate create a test project on github and share the project with me, so I can download and test it.

**Comment by VenkatReddySR** [comment]
Hi Rogeriohsjr,

Good Day!

Am facing sort of similar issue, am using VS professional 2019 and Nunit (along with moq framework). I see the build task fails with below message, do we have support for VS professiona 2019l?


Command failed: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /EnableCodeCoverage "C:\BuildAgent\_work\1\s\Common\Common.Tests\bin\x64\Release\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll"
No suitable test runtime provider found for this run.

**Comment by Rogeriohsjr** [comment]
Hey @VenkatReddySR ,
It does work with VS2019, as you can see on this example:
https://github.com/Rogeriohsjr/AspNetProjectWithNUnit/blob/master/azure-pipelines.yml
The pipeline runs with no issue.

1. Could you share your YML file?
2. Is it possible to share the log when the ConvertCoverage executes? Can you enable the debug when you execute the pipeline as well?

**Comment by VenkatReddySR** [comment]
> Hey @VenkatReddySR ,
> It does work with VS2019, as you can see on this example:
> https://github.com/Rogeriohsjr/AspNetProjectWithNUnit/blob/master/azure-pipelines.yml
> The pipeline runs with no issue.
> 
> 1. Could you share your YML file?
> 2. Is it possible to share the log when the ConvertCoverage executes? Can you enable the debug when you execute the pipeline as well?


Hi Rogeriohsjr,

Thanks for your reply

I have gone through your project, below is my understanding
1) It is pointing to VS Enterprise where as am using professional, 
2) Also for code coverage, **code converter** is pointing to CodeCoverage.exe which is not present in professional
 **Code Coverage Exe File Location** -->Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe
3) Am not sure on how to enable the debug during pipeline execution

Below is Yaml, 

----
  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.3.0'


  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '$(Parameters.solution)'


  - task: VSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: SON.sln

      msbuildArgs: '/p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=$(build.artifactstagingdirectory)\for-deploy\website /p:msbuildArchitecture=x64'

      platform: x64

      configuration: release

      clean: true

      msbuildArchitecture: '$(Parameters.msbuildArchitecture)'

      createLogFile: true

    - task: rogeriohsjr.build-release-task.custom-build-release-task.CoverageConverter@0
    displayName: 'Echo '
    inputs:
      vsTestExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'

      listTestFiles: |  
       **\\*test*.dll
       !**\*TestAdapter.dll
       !**\obj\**
       


  - task: VSTest@2
    displayName: TestAssemblies
    inputs:
      testAssemblyVer2: |  
       **\\*test*.dll
       !**\*TestAdapter.dll
       !**\obj\**
       

      runOnlyImpactedTests: true

      runInParallel: false

      codeCoverageEnabled: '$(Parameters.codeCoverageEnabled)'

      distributionBatchType: basedOnExecutionTime

      diagnosticsEnabled: true



  - task: PublishSymbols@1
    displayName: 'Publish symbols path: '
    inputs:
      SearchPattern: '**\bin\**\*.pdb'


  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(build.sourcesdirectory)'

      Contents: '**\bin\$(BuildConfiguration)\**'

      TargetFolder: '$(build.artifactstagingdirectory)'


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
------------

Below is the log file attachment

----
[8.txt](https://github.com/Rogeriohsjr/AzureDevOpsTask/files/4867585/8.txt)

Thanks
Srikanth

**Comment by Rogeriohsjr** [comment]
Hey @VenkatReddySR ,

1. Code Coverage is enabled only for VS2019 Enterprise as it is in MS Documentation.
["The code coverage feature is available only in Visual Studio Enterprise edition."](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019#requirements)

2. Although If you can see the file the file in the folder, do you know if you execute that manually it generates the xml for you?
You can execute it manually following the instructions on [this doc](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019#analyze-code-coverage-from-the-command-line).

2.1 If you can execute this manually, so we might be able to execute this in the pipeline.
Try to add this YML code into your yml file.
- I think you should not copy the - Task: CoverageConverter@0, use the one you have already in your yml file, but the input section below, I think you should copy.

- task: CoverageConverter@0
  inputs:
    searchFolderForTestFiles: '$(System.DefaultWorkingDirectory)'
    vsTestExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
    vsTestArgs: '/EnableCodeCoverage'
    listTestFiles: '**\bin\**\*test*.dll'
    searchFolderForCodeCoverageFile: '$(System.DefaultWorkingDirectory)'
    temporaryFolderForCodeCoverage: 'Agent.TempDirectory'
    temporaryFileCoveragexml: '\TestResults\DynamicCodeCoverage.coveragexml'
    codeCoverageArgs: 'analyze /output:'
    codeCoverageExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe'

So where is what I changed from the default:

1. I Changed the path to be Professional instead of Enterprise. (Please make sure you have this file in this exactly path)
`
vsTestExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
`

2. I changed the list test files to match the files that you have. On my understand your test project generates a dll called test.dll, right? If so just add this code below there instead of what you did in your yml file. In your log the test project seems different, the test project seems to be "Common.Tests" if that is the case, change the listTestFiles to have *Common.Tests*.dll.
`
listTestFiles: '**\bin\**\*test*.dll'
`

3. I also changed the path for CodeCoverage.exe to use the VS Professional instead of Enterprise. Again, make sure you have this path.

`
codeCoverageExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe'
`

3. Also, execute the task: VSTest@2 before you execute the task: rogeriohsjr.build-release-task.custom-build-release-task.CoverageConverter@0, in other words execute task: rogeriohsjr.build-release-task.custom-build-release-task.CoverageConverter@0 after you build your tests just in case.


I hope that helps.

**Comment by VenkatReddySR** [comment]
> * C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Dynamic Code Coverage Tools

Hey Rogerio,

Thanks for detailed explanation.

I have already tried this, there isnt any option for code coverage in professional (i.e Professional\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe or other equivalent of code coverage.exe is unavailable in professional).

There is an option to install **MS code coverage** nuget package with .net project which contains code coverage.exe and same can be used as a .exe for later code coverage analysis

However appreciate your time and effort on this

Thank you
